### ISSUE TITLE
staleness: replace jax.experimental.optimizers  with jax.optax

### ISSUE THREAD

**Issue by murphyk** [lindermanlab/ssm-jax-refactor#21]
replace jax.experimental.optimizers  with jax.optax eg in https://github.com/lindermanlab/ssm-jax-refactor/blob/main/ssm/inference/laplace_em.py#L7

**Comment by slinderman** [comment]
Great suggestion! I wasn't aware of this library but it looks like just what we need.

**Comment by schlagercollin** [comment]
Thanks for pointing this out. Updated in this commit: https://github.com/lindermanlab/ssm-jax-refactor/commit/207e96135484ff495589f25caa7f2dd5f25d7e3c
