### ISSUE TITLE
ABC imports in Colab

### ISSUE THREAD

**Issue by slinderman** [lindermanlab/ssm-jax-refactor#25]
Hey @schlagercollin, I'm running into an issue with the new ABC imports when running in Colab. Is this a Python versioning issue?

> TypeError                                 Traceback (most recent call last)
[<ipython-input-2-33730756e156>](https://localhost:8080/#) in <module>()
----> 6 from ssm.lds import GaussianLDS
...
[/usr/local/lib/python3.7/dist-packages/ssm/utils.py](https://localhost:8080/#) in <module>()
    101     z2: Sequence[int],
    102     K1: Optional[int] = None,
--> 103     K2: Optional[int] = None,
    104 ):
    105     """
TypeError: 'ABCMeta' object is not subscriptable

**Comment by schlagercollin** [comment]
Arg, you're right. This is necessary for compatibility with 3.10 and it works for 3.9. Colab is on an earlier version though. I'll take a look.

**Comment by schlagercollin** [comment]
Should be fixed in https://github.com/lindermanlab/ssm-jax-refactor/commit/a434f479ab5e826274456ada3a6d43509fcb1c04.
